### ISSUE TITLE
Test LDAP connection/authentication

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#131]
We need to check and configure LDAP in the application to manage 3 different profiles:
- operator
- management
- administrator

See also [this comment](https://github.com/geosolutions-it/C179-DBIAIT/issues/74#issuecomment-733673805) from devops task.

**Comment by lpasquali** [comment]
@mattiagiupponi hello!

I added ldap information I got from PA here:
https://docs.google.com/document/d/1ieocK40MCw74aIpB6HusdtNi9vLIi91egFs_b_yXRcc/edit#heading=h.avjn5rw9cvj

I

**Comment by mattiagiupponi** [comment]
Hi @lpasquali,
Thanks for the link, i have just request for the authorization for see the file.
Could you approve my request?

**Comment by mattiagiupponi** [comment]
Ciao, @lpasquali 
The new changes regarding this issue are available in the following branch: https://github.com/geosolutions-it/C179-DBIAIT/tree/issue-131-ldap-config
I'd like to test before merging them in master, please note that for techinal reasons (since we don't have an account to tests), as discussed with @chpicone, we are using a MapStore account to test the login with ldap
As mentioned, the new environment variables to add are the following:

| VariableName |      valueForTest      |  ProductionValue |
|----------|:-------------:|------:|
| LDAP_OU_APP |  MapStore | ??? | 
| LDAP_GROUP_OPERATORS|    viewers   |   dbiaitoperator | 
| LDAP_GROUP_MANAGERS| editors2 |   dbiaitmanagement  | 
| LDAP_GROP_ADMINS| editors1  |   dbiaitadministrator | 

Plus in the branch as explained during our call, a new enironment for decide the URL path is available in the settings.
| VariableName |      valueForTest      |  ProductionValue |
|----------|:-------------:|------:|
| URL_PATH_PREFIX| qas/  |    | 
| SECURE_SSL_REDIRECT| False  | True   | 

NOTE:
- is important to add the "/" (slash) when you are setting the variable with a value, otherwise if is not needed, please leave it blank
- "SECURE_SSL_REDIRECT" -> If True (default False), the SecurityMiddleware redirects all non-HTTPS requests to HTTPS

**Comment by lpasquali** [comment]
@mattiagiupponi the redirect and URL_PATH_PREFIX are not working, 
uwsgi configuration is like this:
```
[uwsgi]
module = app.wsgi:application
chdir = /apps/dbiait/C179-DBIAIT
#socket = 0.0.0.0:8000
http = 0.0.0.0:8000
uid = dbiait
master = 1
processes = 5
vacuum = true
die-on-term = true
lazy-apps = true
plugins = python3
env = DEBUG=True
env = DATABASE_USER=dbiait_test
env = DATABASE_PASSWORD=OoHai7lahz0ku0i
env = DATABASE_HOST=wg-db-prd.publiacqua.it
env = DATABASE_NAME=dbiait_test
env = FTP_FOLDER=/srv/ftp/
env = SECRET_KEY='#(n3ub-cfj92lsi(+2^(zg1$$toli!9(9rjaff1x6pm8^@qm=!'
env = ALLOWED_HOSTS=[ 'localhost', 'dbi.publiacqua.it', 'dbi-wb01.publiacqua.it', 'dbi-wb02.publiacqua.it' ]
env = LDAP_HOST=ldap://dc01.publiacqua.it:389
env = SECURE_SSL_REDIRECT=True
env = LDAP_USERNAME"CN=webgis_ldap,OU=Users,OU=IT_Services,DC=publiacqua,DC=it"
#env = LDAP_USERNAME='CN=webgis_ldap,OU=Users,OU=IT_Services,DC=publiacqua,DC=it'
env = LDAP_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
env = LDAP_OU_APP=DBIAIT
env = LDAP_GROUP_OPERATORS=dbiaitoperator
env = LDAP_GROUP_MANAGERS=dbiaitmanagement
env = LDAP_GROUP_ADMINS=dbiaitadministrator
env = URL_PATH_PREFIX=qas/
env = SECURE_SSL_REDIRECT=True
```


isn't possible to use django's BASE_URL for that?
I couldn't test ldap because of SECURE_SSL_REDIRECT even if you told me above to already use false, even from local host it redirects to ssl.

if I comment SECURE_SSL_REDIRECT out of settings.py and add URL_PAT_PREFIX="/qas" in environment I get:

![Uploading Screenshot from 2020-11-27 17-01-22.png…]()

**Comment by lpasquali** [comment]
@mattiagiupponi here is the other casistic with URL_PATH_PREFIX commented
![Screenshot from 2020-11-27 17-01-22](https://user-images.githubusercontent.com/1780406/100471218-1ea3ff00-30da-11eb-885d-e32a7550bcde.png)

**Comment by mattiagiupponi** [comment]
Just some notes as remider:
- As we saw together on local environment the "qas" routing is working properly
- By activating URL_PATH_PREFIX looks like that django start searching for // instad of /qas/ (even for static files)
- Looks like that SECURE_SSL_REDIRECT is not working as expected, try to check also those settings:  SESSION_COOKIE_SECURE, CSRF_COOKIE_SECURE, SECURE_PROXY_SSL_HEADER
- Ldap login still not working, we need to add some more log in order to have more detail about the issue and try it again on local environent in debug mode
