### ISSUE TITLE
Add UnitTests

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#132]
We need to add Unit Tests at least for:

- check each different type of transformations
- check each sheet configuration about expected SQL syntax

**Comment by mattiagiupponi** [comment]
- [x] check each different type of transformations
- [ ] check each sheet configuration about expected SQL syntax

**Comment by mattiagiupponi** [comment]
All the tests requested aboce are now available. Please check the PR for more details about how to run them.
Plus i made a complete EXPORT run in order to check also the data in the Export files, following some information about it:
1) SPATIAL join always fails. I'm gonna check the code in order to understand why is failing
2) FOGNATURE processing is failing, so I was not able to check that results. I'm gonna check why is failing

I'm gonna check the code and open another PR if needed for fix this two issues

**Comment by mattiagiupponi** [comment]
Ciao @chpicone the export of the `xlsx` expose some questions for the client
Example:
sheet: `FIUMI`
id: `1500`
Our ouput: `319.6` -> Expected from the client file `320`
Looks like the value on the client file is considered as `INT` instead of `FLOAT`.
If we need to consider it as `INT`, we need to add a new transformation for casting the value

--------------------------------

sheet: `SORGENTI`
id: `26600`
Our ouput: `NO` -> expected from the client file `0`
Looks like the value on the client file is considered as `BINARY` (1/0) instead of `STRING` (SI/NO).
If we need to convert it, we must add some `CASE` or `IF` during the trasformation

--------------------------------

Can you ask to the client how we should behave in the above situations?
Thanks
