### ISSUE TITLE
Export page: UI improvement

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#154]
For the export page the following improvement are necessary:
- change the URL from **/import/dump** to **/export**
- add refresh of the running process otherwise the user cannot understand when the process is completed (put a loading icon)
- show the log when the user click on the status icon (as in the other page)
- if the user do a F5 another export process is queue (trying to send the form data again)
- add pagination to the table

**Comment by mattiagiupponi** [comment]
- [x] change the URL from **/import/dump** to **/export**
- [ ]  add refresh of the running process otherwise the user cannot understand when the process is completed (put a loading icon)
- [ ] show the log when the user click on the status icon (as in the other page)
- [ ] if the user do a F5 another export process is queue (trying to send the form data again)
- [ ]  add pagination to the table
- [ ] fix Logo URL, if we are under qas/ the url always retun to producton link
