### ISSUE TITLE
Prototype graph algorithm using NetworkX

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#180]
We need to prototype an algorithm using NetworkX library in Python to:
- read the network from 2 tables: nodes/edges
- starting from a point (a node over the network) determine the total cost (length) of reachable edges and terminal nodes
Each edge in the network can be tarversable in one direction, both directions or not traversable. Some nodes in the network can be an obstacle.

Final algorithm will be a process scheduled in dramatiq.

**Comment by mattiagiupponi** [comment]
The inestigation is complete and a draft of a graph is ready on this [branch](https://github.com/geosolutions-it/C179-DBIAIT/tree/investigation/%23180_networkx_graph)
Everything will be managed by this class `NetworkFinder` and since is just an investigation, will work only with `condotta_edges` and `condotta_nodes`
This class will calculate:
- find all successors for a specific node with the cost of the path
- find all descendants for a specific node
- find all the boundary nodes for a specific node with the cost of the path
- find all successors for a specific node with the cost of the path avoiding obstacle nodes

Unit test are available [here ](https://github.com/geosolutions-it/C179-DBIAIT/blob/investigation/%23180_networkx_graph/app/tests/network/test_network.py)
