### ISSUE TITLE
Report of anomalies

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#230]
Customer sent an email with the following issues:

- non valorizzati nonostante sia stata valorizzata abitanti_trattati
73300	Depuratori	carico totale trattato [AE]
73400	Depuratori	carico civile trattato [AE]

- non valorizzato
44300	Accumuli	località [testo]

We need also to check anomalies in the column named "28/12/2020" in the google spreadsheet [here](https://docs.google.com/spreadsheets/d/1BT0mlOqiLs_UnGWpwi0xvNFeI5iGikqliicfveG08w8/edit?usp=sharing).

**Comment by mattiagiupponi** [comment]
- [ ] config depuratori
- [ ] config accumuli
- [ ] populate_fognat_tronchi (missing info regarding `diametro`)
- [ ] populate_collett_tronchi (missing info regarding `diametro`)
- [ ] populate_fgn_shape: all information fixed, only the part regarding the new phase is missing. Plus some unittest has been added for this procedure
- [ ] populate_lung_rete_fgn

**Comment by mattiagiupponi** [comment]
Regarding the issue on `populate_lung_rete_fgn` looks like that the problem was caused by the wrong method to calculate the `lung_dep`.
From the old version, the value was calculated with the following sql:
```sql
case when 
    recapito IS NOT NULL or bc.idgis is not NULL
    then lunghezza 
else 0 end lung_tlc 
```
While if we look at the comments on the sheet provided by the client, the `lung_dep` is `somma delle condotte con depurazione = 1` 
So in this case, is enougth to change the previous code with:
```sql
case when
    ft.depurazione::integer = 1
    then lunghezza
else 0 end lung_dep
```
As requested the `depurazione` is calculated in this way
```sql
SET depurazione = 1::BIT WHERE EXISTS(
	SELECT * FROM (
		select c.idgis 
		FROM 
			fgn_condotta c,
			fgn_trattamento d
		where c.sist_acq_dep = d.business_id
	) t WHERE t.idgis = ' || v_table || '.idgis		
);
```
