### ISSUE TITLE
Log: structure of the message

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#236]
In the LOG file that we put in the export zip archive we need to:
- [x] remove the timestamp in each line
- [x] in the {FIELD} placeholder we were the ID of the field (eg 13400) but now we have a letter (eg Q... may be the column name in Excel). The customer is asking to have a description (alias) of the field otherwise to restore the field ID (eg 13400)
- [x] we need to have to label WARNING (in case of validation problem) and ERROR (in case of some errors).

> 2021-01-11 08:45:23,847 ERROR Foglio: Potab_pompe - Riga: 42, Campo: H: Field is not A
> 2021-01-11 08:45:23,848 ERROR Validation: Error occurred during validation of column with ID '37200' in row '43' in sheet 'Potab_pompe':
> TypeError: '>=' not supported between instances of 'str' and 'int'.  

should be:

> ERROR, Foglio: Potab_pompe, Riga: 42, Campo: H, Descrizione: xxxxx
> WARNING, Foglio: Potab_pompe, Riga: 42, Campo: H, Descrizione: xxxxx  

- [x] evaluate if it is possible to provide a custom placeholder to print the value for the field "codice_ato"
- [x] where we have a validation against "ref_year" replace the message with the value of the ref_year:
> WARNING, Foglio: Pozzi, Riga: 12, Campo: anno ristrutturazione, Value is not valid for the ref_year 
> WARNING, Foglio: Pozzi, Riga: 12, Campo: anno ristrutturazione, Value is not valid for the year 2020 
For this waning we need to check the validation rule because the value is 9800 (for the specific item: Pozzi, riga 12) and it should be correct
- [x] each message need to be in a single line (not more)
For example these lines refer to the same error, so we need to have all the message in a single line:
> 2021-01-11 08:45:23,848 ERROR Validation: Error occurred during validation of column with ID '37200' in row '43' in sheet 'Potab_pompe':
> TypeError: '>=' not supported between instances of 'str' and 'int'.

**Comment by mattiagiupponi** [comment]
Progress
- [ ] remove the timestamp in each line
- [ ] in the {FIELD} placeholder we were the ID of the field (eg 13400) but now we have a letter (eg Q... may be the column name in Excel). The customer is asking to have a description (alias) of the field otherwise to restore the field ID (eg 13400)
- [ ] we need to have to label WARNING (in case of validation problem) and ERROR (in case of some errors).
- [ ] evaluate if it is possible to provide a custom placeholder to print the value for the field "codice_ato"
- [ ] where we have a validation against "ref_year" replace the message with the value of the ref_year:
- [ ] each message need to be in a single line (not more)
